import Header from './components/header'
import Sidebar from './components/sidebar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header />
      <div className='flex md:flex-row lg:flex-row sm:flex-col xs:flex-col' style={{height:'100%',backgroundColor: '#0d1117'}}>
        <div className='md:w-1/4 xs:w-full sm:w-full lg:1/4' style={{}}>
        <Sidebar />
        </div>
        <div className='w-3/4 xs:w-full sm:w-full lg:3/4"'>
        {children}
        </div>
      </div>
        </body>
    </html>
  )
}

export const dynamic = 'force-dynamic'
export const revalidate = 0;